minor fixes and improvements

diff --git a/omz b/omz
--- a/omz
+++ b/omz
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 DEFAULT_USER_SHELL="$(echo ${SHELL})"
 ZSH_SHELL="$(command -v zsh)"
 OMZ_TOOLS_URL="https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/"
@@ -63,8 +65,14 @@ getomz()
     return $?
 }
 
+if test -z "$1"
+then
+    echo "Valid arguments are: install, uninstall"
+    exit 1
+fi
+
 case "$1" in
-    install)   check_dependencies; getomz install; install_zsh_theme;;
-    uninstall) check_dependencies; getomz uninstall;;
-    *) exit 1;;
+    "install")   check_dependencies; getomz install; install_zsh_theme;;
+    "uninstall") check_dependencies; getomz uninstall;;
+    *) echo "error: $1: invalid argument"; exit 1;;
 esac
diff --git a/pretty-terminals b/pretty-terminals
--- a/pretty-terminals
+++ b/pretty-terminals
@@ -59,7 +59,7 @@ setup_alacritty()
 
     if test ! -d "${HOME}/.config/alacritty"
     then
-        cp -rv "config/alacritty" "${HOME}/.config"
+        cp --no-preserve=all -rv "config/alacritty" "${HOME}/.config"
     fi
 
     return $?
@@ -67,7 +67,7 @@ setup_alacritty()
 
 if test -z $1
 then
-    echo "Usage: $0 [-t TERMINAL_TYPE]"
+    echo "Usage: ${0} [-t TERMINAL_TYPE]"
     exit 1
 fi
 
@@ -75,7 +75,7 @@ while getopts 't:' arg
 do
     case "$arg" in
         t) TERMINAL_TYPE=$OPTARG;;
-        ?) echo "Usage: ${0} [-t TERMINAL_TYPE]"; exit $?;;
+        ?) echo "error: $arg: invalid argument"; exit $?;;
     esac
 done
 
@@ -88,6 +88,6 @@ fi
 case "${TERMINAL_TYPE}" in
     "termux")       setup_termux;;
     "kitty")        setup_kitty;;
-    "alacritty")  setup_alacritty;;
+    "alacritty")    setup_alacritty;;
     *) echo "Error: ${TERMINAL_TYPE}: unknown type of terminal";;
 esac
