Make script POSIX-compliant and improve some code

diff --git a/pretty-terminals b/pretty-terminals
--- a/pretty-terminals
+++ b/pretty-terminals
@@ -1,19 +1,12 @@
 #!/bin/sh
 
-help()
-{
-    echo "Usage: ${0} {--help|-h} [--setup-termux] [--setup-kitty] [--setup-xterm]"
-
-    return $?
-}
-
 setup_termux()
 {
-    [ "${PREFIX}" != "/data/data/com.termux/files/usr" ] && \
+    test "${PREFIX}" != "/data/data/com.termux/files/usr" && \
         echo ":: ERROR: you are not using Android/Termux" && \
         exit 1
 
-    [ ! -d "/data/data/com.termux/files/usr" ] && \
+    test ! -d "/data/data/com.termux/files/usr" && \
         echo ":: ERROR: termux is not installed" && \
         exit 1
 
@@ -23,15 +16,18 @@ setup_termux()
         apt install -y zsh tigervnc vim git xfce4 kitty thunar \
                         leafpad netsurf proot-distro iproute2 make nala
 
-    [ ! -d "${HOME}/.oh-my-zsh" ] && \
+    if test ! -d "${HOME}/.oh-my-zsh"
+    then
         curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | "${SHELL}"
 
-    [ ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k" ] && \
+    elif test ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k"
+    then
         zsh -c "source ${HOME}/.zshrc && \
                 git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
                     ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/themes/powerlevel10k && \
                 omz theme set powerlevel10k/powerlevel10k && \
                 chsh -s zsh `whoami`"
+    fi
 
     find config/etc/profile.d/*.sh -type f -exec install -Dm 644 {} "${PREFIX}/etc/profile.d/" \;
 
@@ -40,64 +36,74 @@ setup_termux()
 
 setup_kitty()
 {
-    [ ! -x "`command -v wget`" ] && \
-        echo "Please install wget and try again" && exit 1
-    [ ! -x "`command -v kitty`" ] && \
-        echo "Please install kitty and try again" && exit 1
-    [ ! -x "`command -v zsh`" ] && \
-        echo "Please install zsh and try again" && exit 1
-    [ ! -d "${HOME}/.config/kitty" ] && \
-        mkdir "${HOME}/.config/kitty"
-    [ ! -f "${HOME}/.config/kitty/kitty.conf" ] && \
+    for f in curl kitty zsh
+    do
+        if test ! -x "`command -v $f`"
+        then
+            echo "Please install $f and try again" && exit 1
+        fi
+    done
+
+    test ! -d "${HOME}/.config/kitty" && mkdir "${HOME}/.config/kitty"
+
+    test ! -f "${HOME}/.config/kitty/kitty.conf" && \
         cp "config/kitty/kitty.conf" "${HOME}/.config/kitty/kitty.conf"
-    [ ! -d "${HOME}/.fonts" ] && \
-        wget -nc -P "${HOME}/.fonts" \
-            -q https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
-        wget -nc -P "${HOME}/.fonts" \
-            -q https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
-        wget -nc -P "${HOME}/.fonts" \
-            -q https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
-        wget -nc -P "${HOME}/.fonts" \
-            -q https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
-    [ ! -d "${HOME}/.oh-my-zsh" ] && \
-        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | "`command -v zsh`"
-    [ ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k" ] && \
+
+    test ! -d "${HOME}/.fonts" && mkdir $HOME/fonts
+
+    jumpback=`pwd`
+    cd "$HOME/.fonts"
+    curl -fsSLO https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
+    curl -fsSLO https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
+    curl -fsSLO https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
+    curl -fsSLO https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
+    curl -fsSLO https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
+    cd $jumpback && unset $jumpback
+
+    if test ! -d "${HOME}/.oh-my-zsh"
+    then
+        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | zsh
+    elif test ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k"
+    then
         zsh -c "source ${HOME}/.zshrc && \
                 git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
                     ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/themes/powerlevel10k && \
                 omz theme set powerlevel10k/powerlevel10k && \
                 chsh -s /bin/zsh `whoami`"
+    fi
 
-    [ $? = 0 ] && echo "success" || echo "failure"
+    test $? -eq 0 && echo "success" || echo "failure"
 
     return $?
 }
 
 setup_xterm()
 {
-    [ ! -x "`command -v xterm`" ] && \
+    if test ! -x "`command -v xterm`"
+    then
         echo "Please install XTerm and try again" && exit 1
-    [ ! -f "${HOME}/.Xresources" ] && \
-        cp -v ".config/xterm-settings" "${HOME}/.Xresources"
+    elif test ! -f "${HOME}/.Xresources"
+    then
+        cp ".config/xterm-settings" "${HOME}/.Xresources"
+    fi
 
     xrdb -merge "${HOME}/.Xresources"
 
-    [ $? = 0 ] && echo "success" || echo "failure"
+    test $? -eq 0 && echo "success" || echo "failure"
 
     return $?
 }
 
-[ -z $1 ] && help && exit $?
-
-while [ $# -eq 1 ]
+while getopts 't:' arg
 do
-    case $1 in
-        --setup-termux) setup_termux; exit $?;;
-        --setup-kitty) setup_kitty; exit $?;;
-        --setup-xterm) setup_xterm; exit $?;;
-        --help|-h) help; exit $?;;
-        *) [ ! -z $1 ] && echo ":: ERROR: $1: Invalid command" && exit 1;;
+    case $arg in
+        t) TERMINAL_TYPE=$OPTARG;;
+        ?) echo "Usage: ${0} [-t TERMINAL_TYPE]"; exit $?;;
     esac
-    shift
 done
 
+case $TERMINAL_TYPE in
+    termux) setup_termux;;
+    kitty) setup_kitty;;
+    xterm) setup_xterm;;
+esac
