Improve the code a bit

diff --git a/pretty-terminals b/pretty-terminals
--- a/pretty-terminals
+++ b/pretty-terminals
@@ -5,9 +5,11 @@ install_zsh()
 {
     for p in curl zsh git
     do
-        test ! -x `command -v $p` && \
-            echo "Error: $p: no such file was found" && \
-	        exit 1
+        if test ! -x $(command -v $p)
+        then
+            echo "Error: $p: no such file was found"
+	    exit 1
+        fi
     done
 
     if test ! -d "$HOME/.oh-my-zsh"
@@ -32,7 +34,7 @@ install_zsh()
                 git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
                     ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/themes/powerlevel10k && \
                 omz theme set powerlevel10k/powerlevel10k && \
-                chsh -s /bin/zsh `whoami`"
+		chsh -s /bin/zsh $(whoami)"
     fi
 
     return $?
@@ -70,7 +72,7 @@ setup_kitty()
 
     for f in curl kitty zsh
     do
-        if test ! -x "`command -v $f`"
+	    if test ! -x "$(command -v $f)"
         then
             echo "Please install $f and try again" && exit 1
         fi
@@ -92,7 +94,7 @@ setup_kitty()
 
     if test ! -d "${HOME}/.oh-my-zsh"
     then
-        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | zsh
+        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | $SHELL
     elif test ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k"
     then
         zsh -c "source ${HOME}/.zshrc && \
@@ -111,7 +113,7 @@ setup_xterm()
 {
     install_zsh || return 1
 
-    if test ! -x "`command -v xterm`"
+    if test ! -x "$(command -v xterm)"
     then
         echo "Please install XTerm and try again" && exit 1
     elif test ! -f "${HOME}/.Xresources"
@@ -133,6 +135,12 @@ do
         ?) echo "Usage: ${0} [-t TERMINAL_TYPE]"; exit $?;;
     esac
 done
+
+if test -z $TERMINAL_TYPE
+then
+    echo "Usage: ${0} [-t TERMINAL_TYPE]"
+    exit 1
+fi
 
 case $TERMINAL_TYPE in
     termux) setup_termux;;
